---
motd_role: KVM Host
cis_level_1_exclusions: ['1.2.3','1.3.1','1.8','2.2.2','2.2.7','3.4.1','3.4.2','3.4.3','3.4.4','3.4.5','5.2.4','5.2.8','5.3.2']
# 2.2.2 - X11 required for virt-manager
# 5.2.4 - X11 Forwarding enabled for virt-manager
ipaclient_ssl_create_certs: true

kvm_users:
- geoff
kvm_imgvol: /dev/mapper/vg_images-lv_images
kvm_vlans: ['3','4']
kvm_virtual_networks:
- name: Lab_VLAN3
  mode: bridge
  bridge_name: vmbr3
  autostart: true
  state: active
- name: Lab_VLAN4
  mode: bridge
  bridge_name: vmbr4
  autostart: true
  state: active
