---
ovirt_vms:
- name: services
  template: CentOS-8-GenericCloud-8.3.2011
  memory: 16GiB
  cpu_cores: 4
  #clone: true
  cloud_init:
    host_name: services.ocp.home.gatwards.org
    dns_servers: "{{ generic_dns_servers | join(' ') }}"
    dns_search: ocp.home.gatwards.org
    user_name: ansible
    root_password: "{{ vault_vm_root_password }}"
    authorized_ssh_keys: "{{ vault_ansible_ssh_public_key }}"
  cloud_init_nics:
  - nic_name: eth0
    nic_boot_protocol: static
    nic_ip_address: 172.22.5.100
    nic_netmask: 255.255.255.0
    nic_gateway: 172.22.5.1
    nic_on_boot: true
  # - nic_name: eth1
  #   nic_boot_protocol: static
  #   nic_ip_address: 172.22.4.100
  #   nic_netmask: 255.255.255.0
  #   nic_on_boot: true
  cluster: "{{ ovirt_cluster_name }}"
  data_center: "{{ ovirt_datacenter_name }}"
  disks:
  - size: 60GiB
    name: CentOS-8-GenericCloud-8.3.2011
    interface: virtio_scsi
    name_prefix: false
    storage_domain: VMstore1
  nics:
  - name: eth0
    network: VLAN5
  # - name: eth1
  #   network: LAB_EXTERNAL
  state: running
  tag:
    - openshift


ocp_version: '4.8'
