---
motd_role: oVirt Hypervisor
cis_level_1_exclusions: ['1.2.3','1.3.1','1.8','2.2.2','2.2.7','3.4.1','3.4.2','3.4.3','3.4.4','3.4.5','5.2.8','5.3.2']
# 2.2.2 - Bug in hardening - X11 not present

# Common oVirt network parameters
ovirt_mgmt_interface: eno1
ovirt_mgmt_netmask: 255.255.255.0
ovirt_mgmt_gateway: 172.22.4.1
ovirt_migration_interface: eno2
ovirt_migration_netmask: 255.255.255.0
ovirt_trunk_interface: ens5f1
