---
- name: Configure oVirt Engine
  remote_user: svc-ansible
  become: true
  hosts: ovirt_engine
  collections:
  - ovirt.ovirt
  vars_files:
  - vault.yml
  tasks:
  - name: Check if Engine health page is up
    tags:
    - always
    uri:
      url: "http://{{ ansible_fqdn }}/ovirt-engine/services/health"
      status_code: 200
    register: health_page
    retries: 30
    delay: 10
    until: health_page is success

  - name: Obtain SSO token with using username/password credentials
    tags:
    - always
    ovirt.ovirt.ovirt_auth:
      url: https://{{ ansible_fqdn }}/ovirt-engine/api
      username: admin@internal
      password: "{{ vault_ovirt_admin_pass }}"

  - name: Create oVirt VMs
    tags:
    - ovirt_vms
    import_role:
      name: ovirt.ovirt.vm_infra
    vars:
      vms:
      - name: postgresql-vm-0
        template: CentOS-8-GenericCloud-8.3.2011
        memory: 2GiB
        cpu_cores: 2
        #clone: true
        cloud_init:
          host_name: ps.example.com
          root_password: 'mypassword'
          authorized_ssh_keys: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC75ApOJW1sf360AYmh9B57suv+etPYYa6CzvEJjCVZyU+8xPaZR5EacToq9HPYILNAv3TQk1r+K6DKA5+wEpJqm2YzgIPLkZOP1N4Bw19DnAiqIMnDTYa8iIYHOQMpqG/DY6q1/QnP2Gw6r0uTw7zFKH1Vw4DbVJMGOQBJblWFq1G+LSN4j60eiN72kZEMf3fQgLCKUzDdbOUkjJnl/4/SUq5lncMBm88efiJLNwdJzelGkH5QveNioiQ/mXP/DlnLYiCKHh1qJlaD/OGlEuHJSnDD9uD4TknEi8AFqLTDc4XZZgUWF5RWSUwxMIiBuyMtr5Zma20dQpdwqYZT6LcNcMokHHAQ+S/cuibtR/YQ3PsYubUIAbCfeIHjKRdBDUP5ZE/VfybKTE/rlAUQCzpt5w5iBWr3qo2iW7gW/Rvlt78bqCHETnCNHLIT5mm9koA0+kr2dNmiUnb91KpdpNs4tLveVYGtN8tJHL4NDSHqiEeOYklV+uLL2gN6kziB53c= svc-ansible@ansible.core.home.gatwards.org
        cloud_init_nics:
        - nic_name: nic1
          nic_boot_protocol: static
          nic_ip_address: 172.22.3.101
          nic_netmask: 255.255.255.0
          nic_gateway: 172.22.3.1
          nic_on_boot: true
        cluster: "{{ ovirt_cluster_name }}"
        disks:
        - size: 20GiB
          name: CentOS-8-GenericCloud-8.3.2011
          interface: virtio
          name_prefix: false
          storage_domain: VMstore1
        nics:
        - name: nic1
          network: VLAN3
          #profile_name: VLAN3
          interface: virtio
        state: running
        tag:
          - pgsql
          - httpd


  - name: Always revoke the SSO token
    tags:
    - always
    ovirt_auth:
      state: absent
      ovirt_auth: "{{ ovirt_auth }}"
