---
- name: Deploy oVirt VMs for kolla
  remote_user: svc-ansible
  become: true
  hosts: ovirt_engine
  collections:
  - ovirt.ovirt
  vars_files:
  - vault.yml
  tasks:
  - name:
    include_tasks: tasks/create_ovirt_vms.yml
    vars:
      ovirt_vms: "{{ hostvars[groups['kolla'][0]].ovirt_vms }}"
