apiVersion: v1
baseDomain: ocp.home.gatwards.org
metadata:
  name: lab

compute:
- name: worker
#  hyperthreading: Enabled
  platform: {}
  replicas: 0


controlPlane:
#  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 10.100.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUZ2nVg/ZCPS7K1g50sr6uytl9qVy191OM6K6FuRKT5eP2ta161HIZqoxrFzcn3Ib7Xo1zu7du97iicvoQ1HGka9XA2YNYPGiq0RS2nAJsfdIN9/kAvHTh3JWCptfxcaljKScxW3N8LFC8ezgd4Af2D5xhtu0FxD/a1dbzOmryqPup1TH4+vXywf6envJNSjT/jTLZgB+UL8rIAOhr2jCW+ikXz6Y+CSL35vpD6v+WbsedplxVd+3h0FN7KrlMVBTzAxsTAyx5/SdDGd1hwSqB7PjLyNygqtpIWbrGlbEE+Agu//FLluf6gvncn2kHkiVH7M2fkbh/BimE6hkUbG8tRA7/ZCtLLVMPmXVU+7vu+qgqKvY/OSgy/e1IE09bdtDMI+6zQ3G+48dpO61mSvz/QnFZeobyivCEUSyrsxbeBK7gfnpiSh6gclBxGzdCC/RllbU/sEb4RqqlYF4gVOk0nF/TbrXmoX/EH9WeYOHaO3JvpLcjoyVXpsXYwzd88Hk= root@services.ocp.home.gatwards.org'
