apiVersion: v1
baseDomain: okd.home.gatwards.org
metadata:
  name: lab

compute:
- name: worker
#  hyperthreading: Enabled
  platform: {}
  replicas: 0


controlPlane:
#  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 10.100.0.0/16

platform:
  none: {}

fips: false

pullSecret: '{"auths":{"fake":{"auth": "bar"}}}'
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDCo0seMFNnSgezhW0NfoyeAtJbBL20CzDkvVe0Z7FQUKDYQHieXEoZ2Gr8UXtbkX+AnhKV2JBQzplhhV3J88r016YashuZETh7tGW5dZIFsarhakTMcXuX499YtW5yb3WDUUmGxKBW7jk21Gjum+eKsvVEN2JpmfwbsNbAdh6uSl7Ok+rNgq6TI6Zf9yMpUdIBzkkshJdT1GUhpz8QfAAOFICyiteolLIhMpd/FdtHFCPTxlR1+TmEj9j9pNMx03Pb1NHOYyJGBvL2rp430rLVQ1PWnP3tgm7tf1c6By/OSjrkDS2nL6t036aA1qkT9FeucBcRuwZnrOdf4trHe4yf2hkvr+GDDtIQ3UngC6D8isN1LP2QNe0m65/oQopeSDneBPpANypHLnS5KxQFSOk0klxJ+auO+zVUzD/cdrUBWr11o2LTIh/wkA93E38cr7akEAVGwCCZ2pt36yN4lj70QxxqhWjg2R0KHVNnFzADbepZwgkEqnroAXohgj6FtCE='
